# Exercise 6: NumPy Basics

**Goals**
- Understand what NumPy is and why it is widely used in scientific computing
- Learn how to create and operate arrays (1D, 2D): addition, subtraction, multiplication, division
- Explore useful NumPy functions like `np.linspace`, `np.arange`, `np.zeros`, `np.ones`

In [2]:
import numpy as np

# --- 1. Creating arrays ---
arr1 = np.array([1, 2, 3, 4, 5])
print("Array:", arr1)

arr2 = np.zeros(5)
print("Zeros:", arr2)

arr3 = np.ones((2, 3))
print("Ones (2x3):\n", arr3)

arr4 = np.arange(0, 10, 2)
print("Arange 0-10 step 2:", arr4)

arr5 = np.linspace(0, 1, 5)
print("Linspace 0-1 with 5 points:", arr5)


Array: [1 2 3 4 5]
Zeros: [0. 0. 0. 0. 0.]
Ones (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]
Arange 0-10 step 2: [0 2 4 6 8]
Linspace 0-1 with 5 points: [0.   0.25 0.5  0.75 1.  ]


In [3]:
# --- 2. Indexing and slicing ---
data = np.array([10, 20, 30, 40, 50])
print("data[0]:", data[0])
print("data[1:4]:", data[1:4])
print("data[-1]:", data[-1])

data[0]: 10
data[1:4]: [20 30 40]
data[-1]: 50


In [5]:
# --- 3. Array operations ---
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a+b:", a + b)
print("a*b:", a * b)
print("a**2:", a**2)

# dot product
print("dot(a,b):", np.dot(a,b)) # 1*4+2*5+3*6 = 32

# cross product
print("cross(a, b):", np.cross(a, b)) 

a+b: [5 7 9]
a*b: [ 4 10 18]
a**2: [1 4 9]
dot(a,b): 32
cross(a, b): [-3  6 -3]


In [17]:
# --- 4. Column vectors (3x1) ---
a_col = np.array([[1], [2], [3]])
b_col = np.array([[4], [5], [6]])
print("Column vector a:\n", a_col)
print("Column vector b:\n", b_col)
print("a_col + b_col:\n", a_col + b_col)
print("a_col * b_col:\n", a_col * b_col)

Column vector a:
 [[1]
 [2]
 [3]]
Column vector b:
 [[4]
 [5]
 [6]]
a_col + b_col:
 [[5]
 [7]
 [9]]
a_col * b_col:
 [[ 4]
 [10]
 [18]]


In [21]:
# --- 5. 2D arrays ---
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)
print("Shape:", matrix.shape)
print("matrix[0,1]:", matrix[0,1])

# Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A @ B (matrix product):\n", A @ B)

Matrix:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
matrix[0,1]: 2
Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A @ B (matrix product):
 [[19 22]
 [43 50]]


In [7]:
# --- 6. Useful functions ---
arr1 = np.array([1, 2, 3, 4, 5])
print("Mean of arr1:", np.mean(arr1))
print("Standard deviation of arr1:", np.std(arr1))
print("Max of arr1:", np.max(arr1))

Mean of arr1: 3.0
Standard deviation of arr1: 1.4142135623730951
Max of arr1: 5


In [19]:
# --- 7. Mini Exercise ---
# Simulate 1000 measurements of a Gaussian-distributed variable
# with mean=0 and sigma=1

samples = np.random.normal(0, 1, 1000)
print("First 10 samples:", samples[:10])

print("Mean:", np.mean(samples))
print("Std Dev:", np.std(samples))

First 10 samples: [ 0.27017776  0.57281785  2.76203996  0.85435987 -0.42435159 -1.51404309
 -0.22156007 -0.31571471 -0.74835737  2.57349909]
Mean: -0.03064101951982734
Std Dev: 1.0313609696145891


## Exercise 1: Clean and summarize detector data

A sensor recorded repeated temperature measurements. The value `-999.0` is an error code rather than a physical measurement.

1. Use a Boolean mask to select only values greater than `-100`.
2. Print the cleaned array.
3. Calculate its mean and standard deviation with NumPy.
4. Count how many measurements are more than one standard deviation away from the mean.

Hint: `temperatures[temperatures > -100]` applies a condition to every element of the array.

In [ ]:
temperatures = np.array([20.1, 20.4, -999.0, 19.9, 20.2, 21.0, 19.8, -999.0])

# TODO: Make a Boolean mask and create cleaned_temperatures.

# TODO: Calculate and print the mean and standard deviation.

# TODO: Count values more than one standard deviation from the mean.

## Exercise 2: Solve a system of equations

Consider the system

$$
2x+y-z=8,\qquad -3x-y+2z=-11,\qquad -2x+y+2z=-3.
$$

1. Store the coefficients in a matrix `A` and the right-hand side in an array `b`.
2. Use `np.linalg.solve(A, b)` to find `x`, `y`, and `z`.
3. Calculate `A @ solution` and compare it with `b`.
4. Use `np.allclose(A @ solution, b)` to test the solution numerically.

In [ ]:
# TODO: Define the 3x3 matrix A and the array b.

# TODO: Solve A @ solution = b.

# TODO: Print the solution and verify it with A @ solution.

# TODO: Use np.allclose() for a final True/False check.